version: "3.8"
services:
  database:
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: spacemy
      MYSQL_PASSWORD: sample
      MYSQL_ROOT_PASSWORD: sample
    ports:
      - "3306:3306"
  spacemy:
    build: ./
    ports:
      - "80:80"
    volumes:
      - ./container/website/logs:/var/log/nginx
      - ./container/website/data:/var/www/data